name: Test and Notify

on:
  push:
    branches:
      - main

jobs:
  test-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Ensure smtplib or other dependencies are installed

      - name: Run tests
        run: |
          python test_script.py  # Your test script

      - name: Send email
        run: |
          python send_email.py  # Your email script
